
title: &site_title Sprachassistent
description: >- # this means to ignore newlines until "baseurl:"
  Proof-of-Concept und Dokumentation eines im Rahmen des Informatikprojekts entstandenen Open-Source Sprachassistenten.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: LeakyAbstractions/pretty-docs
branding:
  icon:
    name: icon_mic_alt
  highlight: Sprachassistent
  bold: Unbennant
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html

#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
github: [metadata]
